/** 获取活动信息 */
export const ACTIVITY_GET_START = 'ACTIVITY_GET_START'
export const ACTIVITY_GET_SUCCESS = 'ACTIVITY_GET_SUCCESS'
export const ACTIVITY_GET_FAIL = 'ACTIVITY_GET_FAIL'
export const ACTIVITY_GET_END = 'ACTIVITY_GET_END'
export const ACTIVITY_BROADCAST_GET_START = 'ACTIVITY_BROADCAST_GET_START'
export const ACTIVITY_BROADCAST_GET_SUCCESS = 'ACTIVITY_BROADCAST_GET_SUCCESS'
export const ACTIVITY_BROADCAST_GET_FAIL = 'ACTIVITY_BROADCAST_GET_FAIL'
export const ACTIVITY_BROADCAST_GET_END = 'ACTIVITY_BROADCAST_GET_END'
/** 获取活动信息 */

export const PRODUCT_DETAIL_RESET_INFO = 'PRODUCT_DETAIL_RESET_INFO'
