/** 获取首页广告BANNER */
export const INDEX_BANNER_GET_START = 'INDEX_BANNER_GET_START'
export const INDEX_BANNER_GET_SUCCESS = 'INDEX_BANNER_GET_SUCCESS'
export const INDEX_BANNER_GET_FAIL = 'INDEX_BANNER_GET_FAIL'
export const INDEX_BANNER_GET_END = 'INDEX_BANNER_GET_END'
/** 获取首页广告BANNER */

// 获取首页分类
export const INDEX_CATEGORY_GET_SUCCESS = 'INDEX_CATEGORY_GET_SUCCESS'
export const INDEX_CATEGORY_GET_FAIL = 'INDEX_CATEGORY_GET_FAIL'
// 获取首页特色分类
export const INDEX_FEATURE_GET_SUCCESS = 'INDEX_FEATURE_GET_SUCCESS'
export const INDEX_FEATURE_GET_FAIL = 'INDEX_FEATURE_GET_FAIL'

/** 首页收藏数据 */
export const INDEX_SUBSCRIBE_SET_DATA = 'INDEX_SUBSCRIBE_SET_DATA'
export const INDEX_SUBSCRIBE_RESET = 'INDEX_SUBSCRIBE_RESET'
/** 首页收藏数据 */

/** 获取热销产品 */
export const HOT_PRODUCTS_GET_START = 'HOT_PRODUCTS_GET_START'
export const HOT_PRODUCTS_GET_SUCCESS = 'HOT_PRODUCTS_GET_SUCCESS'
export const HOT_PRODUCTS_GET_FAIL = 'HOT_PRODUCTS_GET_FAIL'
export const HOT_PRODUCTS_GET_END = 'HOT_PRODUCTS_GET_END'
export const HOT_PRODUCTS_LOADING_START = 'HOT_PRODUCTS_LOADING_START'
export const HOT_PRODUCTS_LOADING_END = 'HOT_PRODUCTS_LOADING_END'
export const HOT_PRODUCTS_LOADING_SUCCESS = 'HOT_PRODUCTS_LOADING_SUCCESS'
export const HOT_PRODUCTS_LOADING_FAIL = 'HOT_PRODUCTS_LOADING_FAIL'
/** 获取热销产品 */

/** 获取产品分类 */
export const GET_PRODUCT_CATEGORY_START = 'GET_PRODUCT_CATEGORY_START'
export const GET_PRODUCT_CATEGORY_SUCCESS = 'GET_PRODUCT_CATEGORY_SUCCESS'
export const GET_PRODUCT_CATEGORY_END = 'GET_PRODUCT_CATEGORY_END'
export const GET_PRODUCT_CATEGORY_FAIL = 'GET_PRODUCT_CATEGORY_FAIL'
export const GET_CATEGORY_PRODUCTS_ID = 'GET_CATEGORY_PRODUCTS_ID'
export const SET_CATEGORY_PRODUCTS_ID = 'SET_CATEGORY_PRODUCTS_ID'
export const SET_ACTIIVE_CATEGORY = 'SET_ACTIIVE_CATEGORY'
/** 获取产品分类 */

/** 获取产品列表 */
export const PRODUCT_LIST_GET_START = 'PRODUCT_LIST_GET_START'
export const PRODUCT_LIST_GET_SUCCESS = 'PRODUCT_LIST_GET_SUCCESS'
export const PRODUCT_LIST_GET_FAIL = 'PRODUCT_LIST_GET_FAIL'
export const PRODUCT_LIST_GET_END = 'PRODUCT_LIST_GET_END'
export const PRODUCT_LIST_LOADING_START = 'PRODUCT_LIST_LOADING_START'
export const PRODUCT_LIST_LOADING_SUCCESS = 'PRODUCT_LIST_LOADING_SUCCESS'
export const PRODUCT_LIST_LOADING_FAIL = 'PRODUCT_LIST_LOADING_FAIL'
export const PRODUCT_LIST_LOADING_END = 'PRODUCT_LIST_LOADING_END'
export const PRODUCT_LIST_CLEAR = 'PRODUCT_LIST_CLEAR'


/** 内容管理系统相关 */
export const CMSLIST_SET_MENU_CURRENT_TAB = 'CMSLIST_SET_MENU_CURRENT_TAB'
export const CMSLIST_MENU_GET_START = 'CMSLIST_MENU_GET_START'
export const CMSLIST_MENU_GET_SUCCESS = 'CMSLIST_MENU_GET_SUCCESS'
export const CMSLIST_MENU_GET_FAIL = 'CMSLIST_MENU_GET_FAIL'
export const CMSLIST_MENU_GET_END = 'CMSLIST_MENU_GET_END'
export const CMSLIST_GET_START = 'CMSLIST_GET_START'
export const CMSLIST_GET_SUCCESS = 'CMSLIST_GET_SUCCESS'
export const CMSLIST_GET_FAIL = 'CMSLIST_GET_FAIL'
export const CMSLIST_GET_END = 'CMSLIST_GET_END'
export const CMSLIST_CLEAR = 'CMSLIST_CLEAR'
export const CMSLIST_DETAIL_GET_SUCCESS = 'CMSLIST_DETAIL_GET_SUCCESS'
/** 内容管理系统相关 */


// 消息相关
export const MESSAGE_SET_COUNT = 'MESSAGE_SET_COUNT'
export const MESSAGE_GET_LIST = 'MESSAGE_GET_LIST'

// 保险知识
export const GET_INSURANCE_KNOWLEDGE_START = 'GET_INSURANCE_KNOWLEDGE_START'
export const GET_INSURANCE_KNOWLEDGE_SUCCESS = 'GET_INSURANCE_KNOWLEDGE_SUCCESS'
export const GET_INSURANCE_KNOWLEDGE_FAIL = 'GET_INSURANCE_KNOWLEDGE_FAIL'
export const GET_INSURANCE_KNOWLEDGE_END = 'GET_INSURANCE_KNOWLEDGE_END'

// 代理人签约协议
export const GET_SIGN_AGREEMENT_START = 'GET_SIGN_AGREEMENT_START'
export const GET_SIGN_AGREEMENT_SUCCESS = 'GET_SIGN_AGREEMENT_SUCCESS'
export const GET_SIGN_AGREEMENT_FAIL = 'GET_SIGN_AGREEMENT_FAIL'
export const GET_SIGN_AGREEMENT_END = 'GET_SIGN_AGREEMENT_END'

/* 缓存更新用户信息 */
export const UPDATE_CACHE_USER_INFO = 'UPDATE_CACHE_USER_INFO'
export const RESET_CACHE_USER_INFO = 'RESET_CACHE_USER_INFO'
/* 缓存更新用户信息 */

/** 代理人注册 */
export const AGENT_REGISTER_START = 'AGENT_REGISTER_START'
export const AGENT_REGISTER_SUCCESS = 'AGENT_REGISTER_SUCCESS'
export const AGENT_REGISTER_FAIL = 'AGENT_REGISTER_FAIL'
export const AGENT_REGISTER_END = 'AGENT_REGISTER_END'
export const AGENT_REGISTER_FLAG_SET = 'AGENT_REGISTER_FLAG_SET'
export const AGENT_REGISTER_FLAG_CLEAR = 'AGENT_REGISTER_FLAG_CLEAR'
/** 代理人注册 */

// 代理人注册表单数据更新
export const AGENT_REGISTER_GET_USER_DETAIL = 'AGENT_REGISTER_GET_USER_DETAIL'
export const AGENT_REGISTER_FORM_UPDATE = 'AGENT_REGISTER_FORM_UPDATE'
export const AGENT_REGISTER_FORM_RESET = 'AGENT_REGISTER_FORM_RESET'

/** 获取验证码 */
export const SECURITY_CODE_GET_START = 'SECURITY_CODE_GET_START'
export const SECURITY_CODE_GET_SUCCESS = 'SECURITY_CODE_GET_SUCCESS'
export const SECURITY_CODE_GET_FAIL = 'SECURITY_CODE_GET_FAIL'
export const SECURITY_CODE_GET_END = 'SECURITY_CODE_GET_END'
/** 获取验证码 */

/** 渠道协议 */
export const GET_PROTPCOL_START = 'GET_PROTPCOL_START'
export const GET_PROTPCOL_SUCCESS = 'GET_PROTPCOL_SUCCESS'
export const GET_PROTPCOL_FAIL = 'GET_PROTPCOL_FAIL'
export const GET_PROTPCOL_END = 'GET_PROTPCOL_END'
export const PROTPCOL_SAVE_DATA = 'PROTPCOL_SAVE_DATA'
export const PROTPCOL_SAVE_TYPE = 'PROTPCOL_SAVE_TYPE'
/** 渠道协议 */

/** 合同邀请码 */
export const GET_CONTRACT_START = 'GET_CONTRACT_START'
export const GET_CONTRACT_SUCCESS = 'GET_CONTRACT_SUCCESS'
export const GET_CONTRACT_FAIL = 'GET_CONTRACT_FAIL'
export const GET_CONTRACT_END = 'GET_CONTRACT_START'
/** 合同邀请码 */

/** 地址信息 */
export const GET_ADDRESS_LIST = 'GET_ADDRESS_LIST'
/** 地址信息 */

/** 考试 */
export const GET_QUESTIONS_SUCCESS = 'GET_QUESTIONS_SUCCESS'
export const GET_QUESTIONS_FAIL = 'GET_QUESTIONS_FAIL'
export const SAVE_QUESTIONS_SUCCESS = 'SAVE_QUESTIONS_SUCCESS'
export const SAVE_QUESTIONS_FAIL = 'SAVE_QUESTIONS_FAIL'
/** 考试 */

/** 公司选择弹窗 */
export const COMPANY_SET_CONFIG = 'COMPANY_SET_CONFIG'
export const COMPANY_CLEAR_CONFIG = 'COMPANY_CLEAR_CONFIG'
/** 公司选择弹窗 */

/** 客户列表和详情 */
export const CUSTOMER_RESET_POLICY = 'CUSTOMER_RESET_POLICY'
export const CUSTOMER_RESET_ADD = 'CUSTOMER_RESET_ADD'
export const CUSTOMER_RESET_LOSS = 'CUSTOMER_RESET_LOSS'
export const CUSTOMER_ADD = 'CUSTOMER_ADD'
export const CUSTOMER_LOSS = 'CUSTOMER_LOSS'
export const CUSTOMER_POLICY = 'CUSTOMER_POLICY'
export const CUSTOMER_CHANGE_INFO = 'CUSTOMER_CHANGE_INFO'
export const CUSTOMER_RESET_STATUS = 'CUSTOMER_RESET_STATUS'
export const CUSTOMER_DETAIL_LOADING_START = 'CUSTOMER_DETAIL_LOADING_START'
export const CUSTOMER_DETAIL_LOADING_END = 'CUSTOMER_DETAIL_LOADING_END'
export const CUSTOMER_DETAIL_GET_INFO_SUCCESS = 'CUSTOMER_DETAIL_GET_INFO_SUCCESS'
export const CUSTOMER_DETAIL_GET_INFO_FAIL = 'CUSTOMER_DETAIL_GET_INFO_FAIL'
export const CUSTOMER_DETAIL_SET_INFO = 'CUSTOMER_DETAIL_SET_INFO'
export const CUSTOMER_DETAIL_CLEAR_INFO = 'CUSTOMER_DETAIL_CLEAR_INFO'
/** 客户列表和详情 */

/** 团队权限 */
export const GET_GROUP_TAB_START = 'GET_GROUP_TAB_START'
export const GET_GROUP_TAB_END = 'GET_GROUP_TAB_END'
export const GET_GROUP_TAB_SUCCESS = 'GET_GROUP_TAB_SUCCESS'
export const GET_GROUP_TAB_FAIL = 'GET_GROUP_TAB_FAIL'

export const GET_GROUP_DETAIL_INFO = 'GET_GROUP_DETAIL_INFO'
export const CLEAR_GROUP_DETAIL_INFO = 'CLEAR_GROUP_DETAIL_INFO'
/** 团队权限 */

/** 更多标签 */
export const ADD_LABEL_ADD_LIST = 'ADD_LABEL_ADD_LIST'
export const ADD_LABEL_REMOVE_INDEX = 'ADD_LABEL_REMOVE_INDEX'
export const ADD_LABEL_CLEAR = 'ADD_LABEL_CLEAR'
/** 更多标签 */

/** jim */
// eslint-disable-next-line
export const PUSH_MSG_LIST = 'PUSH_MSG_LIST'  // 单聊聊天记录push
// eslint-disable-next-line
export const MSG_RECEIPT_CHANGE = 'MSG_RECEIPT_CHANGE' // 发送的消息回执变化
