/* 用户登录 */
export const USER_LOGIN_START = 'USER_LOGIN_START'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGIN_END = 'USER_LOGIN_END'
/* 用户登录 */

/* 用户登出 */
export const USER_LOGOUT_START = 'USER_LOGOUT_START'
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS'
export const USER_LOGOUT_FAIL = 'USER_LOGOUT_FAIL'
export const USER_LOGOUT_END = 'USER_LOGIN_END'
/* 用户登出 */

/* 获取用户信息 */
export const GET_USER_INFO_START = 'GET_USER_INFO_START'
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS'
export const GET_USER_INFO_FAIL = 'GET_USER_INFO_FAIL'
export const GET_USER_INFO_END = 'GET_USER_INFO_END'
/* 获取用户信息 */

/* 是否允许用户登录 */
export const USER_CHECK_ALLOWED_LOGIN = 'USER_CHECK_ALLOWED_LOGIN'
/* 是否允许用户登录 */

/* 系统信息state */
export const SYSTEM_SET_VERSION = 'SYSTEM_SET_VERSION'
export const SYSTEM_SET_TYPE = 'SYSTEM_SET_TYPE'
/* 系统信息state */

// 全局loading toask 等状态
export const VUX_LOADER_SHOW = 'VUX_LOADER_SHOW'
export const VUX_LOADER_HIDE = 'VUX_LOADER_HIDE'
export const VUX_TOAST_SHOW = 'VUX_TOAST_SHOW'
export const VUX_POPUP_TEL_SHOW = 'VUX_POPUP_TEL_SHOW'
export const VUX_POPUP_TEL_HIDE = 'VUX_POPUP_TEL_HIDE'
export const VUX_QRCODE_SHOW = 'VUX_QRCODE_SHOW'
export const VUX_QRCODE_HIDE = 'VUX_QRCODE_HIDE'

/** 分享提示弹窗 */
export const SHARE_PROMPT_TOGGLE = 'SHARE_PROMPT_TOGGLE'
export const DIALOG_PROTOCOL_TOGGLE = 'DIALOG_PROTOCOL_TOGGLE'
export const DIALOG_CONTRACT_TOGGLE = 'DIALOG_CONTRACT_TOGGLE'
export const DIALOG_COMPANY_TOGGLE = 'DIALOG_COMPANY_TOGGLE'
export const DIALOG_HIDE_ALL = 'DIALOG_HIDE_ALL'

/** 条款预览弹框信息 */
export const SET_CONTENT_URI = 'SET_CONTENT_URI'
export const REMOVE_CONTENT_URI = 'REMOVE_CONTENT_URI'
/** 条款预览弹框信息 */

/** 分享图标URL */
export const GET_SHARE_ICON_URL = 'GET_SHARE_ICON_URL'

export const COMMON_TITLE_SET_TEXT = 'COMMON_TITLE_SET_TEXT'
export const COMMON_TITLE_SET_TYPE = 'COMMON_TITLE_SET_TYPE'
export const COMMON_TITLE_SET_RIGHT = 'COMMON_TITLE_SET_RIGHT'
export const COMMON_TITLE_SET_LEFT = 'COMMON_TITLE_SET_LEFT'
export const COMMON_TITLE_SET_ALL = 'COMMON_TITLE_SET_ALL'

/** 获取App 相关信息 */
export const GET_APP_INFO_START = 'GET_APP_INFO_START'
export const GET_APP_INFO_SUCCESS = 'GET_APP_INFO_SUCCESS'
export const GET_APP_INFO_FAIL = 'GET_APP_INFO_FAIL'
export const GET_APP_INFO_END = 'GET_APP_INFO_END'
/** 获取App 相关信息 */

/** 获取验证码 */
export const SECURITY_CODE_GET_START = 'SECURITY_CODE_GET_START'
export const SECURITY_CODE_GET_SUCCESS = 'SECURITY_CODE_GET_SUCCESS'
export const SECURITY_CODE_GET_FAIL = 'SECURITY_CODE_GET_FAIL'
export const SECURITY_CODE_GET_END = 'SECURITY_CODE_GET_END'
/** 获取验证码 */

/** 获取枚举类型开始 */
export const GET_DIC_TYPE_START = 'GET_DIC_TYPE_START'
export const GET_DIC_TYPE_SUCCESS = 'GET_DIC_TYPE_SUCCESS'
export const GET_DIC_TYPE_FAIL = 'GET_DIC_TYPE_FAIL'
export const GET_DIC_TYPE_END = 'GET_DIC_TYPE_END'
/** 获取枚举类型结束 */

/** 获取枚举类型开始 */
export const GET_ENUM_START = 'GET_ENUM_START'
export const GET_ENUM_SUCCESS = 'GET_ENUM_SUCCESS'
export const GET_ENUM_FAIL = 'GET_ENUM_FAIL'
export const GET_ENUM_END = 'GET_ENUM_END'
/** 获取枚举类型结束 */


/** 获取用户权限 */
export const GET_USER_ENTRY_START = 'GET_USER_ENTRY_START'
export const GET_USER_ENTRY_SUCCESS = 'GET_USER_ENTRY_SUCCESS'
export const GET_USER_ENTRY_FAIL = 'GET_USER_ENTRY_FAIL'
export const GET_USER_ENTRY_END = 'GET_USER_ENTRY_END'
/** 获取用户权限 */
